### ISSUE TITLE
Build artifact containing changes in source branch

### ISSUE THREAD

**Issue by shahzadatta** [MicrosoftDocs/pipelines-php#1]
Hi,

I am new to Azure DevOps. Followed the documentation to setup a build pipeline. The configuration is;
**Framework**: Laravel 5.4 (PHP) 
**Repo**: Azure Repo (Git based)
**Agent**: Self hosted (registered with Azure DevOps and online)
**Source branch**: master (Trigger is enabled for continuous integration - Shallow depth is set to 1)
My build pipeline contain two tasks. **Copy Files to** and **Publish Artifact**.
Current behavior:  All of the git repo history is traversed (all branches are pulled as per the log). All of the files are copied from the master branch and published as Artifact. (Approx 8089 files and it took 15 mins to complete the build process)
Desired behavior: Only master branch is pulled and reviewed for changes. Only modified, newly added files should be  published as artifact. (On a usual build it would be 4-10 files and shall take 10-20 seconds to publish). 
What am I missing? Is there a way to publish the changes on source branch as artifact? 
Also, with my older deployment stack, I was able to link up files and folders that are not affected by a build or release and just link them with new release (avoiding the copy paste of these files folders). How do we handle that with Azure DevOps?

**Comment by shahzadatta** [comment]
@DavidStaheli Can you please respond to my question above? Thank you.

**Comment by davidstaheli** [comment]
Hi @shahzadatta.  Thanks for your question.  I'm away for the next several days but want to help when I can.  Could you please log this question at the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)?  It will get better attention there in case I can't get back to you soon enough.

**Comment by shahzadatta** [comment]
@DavidStaheli Thanks for the pointer. I posted my question on Azure DevOps Developer Community. Here is the link, in case you are interested.  https://developercommunity.visualstudio.com/content/problem/399841/azure-dev-ops-build-artifact-containing-only-chang.html

Thank you again and really appreciate the response with your busy routine. Super Awesome.
